-- Course
CREATE TABLE course (
  COURSEID VARCHAR2(26),
  COURSE_NAME VARCHAR2(58),
  COURSE_DURATION NUMBER(1)
);

-- Training
CREATE TABLE training (
  TEACHERID VARCHAR2(26),
  COURSEID VARCHAR2(26),
  TRAINING_YEAR VARCHAR2(6),
  TRAINING_LOCATION VARCHAR2(6)
);

-- Teacher
CREATE TABLE teacher (
  TEACHERID VARCHAR2(26),
  TEACHER_ROLE VARCHAR2(23),
  TEACHER_NAME VARCHAR2(15)
);

-- Children_Incidents
CREATE TABLE children_incidents (
  INCIDENTID VARCHAR2(26),
  INCIDENT_DATE DATE,
  CHILDRENID VARCHAR2(26),
  TYPEID VARCHAR2(26),
  TEACHERID VARCHAR2(26),
  INCIDENTS_COST NUMBER(3)
);

-- IncidentsType
CREATE TABLE incidentstype (
  TYPEID VARCHAR2(26),
  TYPE_DESCRIPTION VARCHAR2(37)
);

-- Children
CREATE TABLE children (
  CHILDRENID VARCHAR2(26),
  CHILD_GENDER VARCHAR2(6),
  CHILD_NAME VARCHAR2(17),
  CHILD_AGE NUMBER(1),
  PARENTID VARCHAR2(26),
  CENTERID VARCHAR2(26)
);

-- Daycare_Center
CREATE TABLE daycare_center (
  CENTERID VARCHAR2(26),
  CENTER_CAPACITY NUMBER(3),
  CENTER_POSTCODE NUMBER(4),
  CENTER_PHONENUMBER NUMBER(10),
  CENTER_OPENINGHOUR VARCHAR2(7)
);

-- Parents
CREATE TABLE parents (
  PARENTID VARCHAR2(26),
  PARENT_NAME VARCHAR2(17),
  PARENT_POSTCODE NUMBER(4)
);
